CREATE DATABASE  IF NOT EXISTS `BURNING_BROS_SCHEMA`;
USE `BURNING_BROS_SCHEMA`;

--
-- Create table
--

DROP TABLE IF EXISTS `DT_MAINTENANCE`;

CREATE TABLE `DT_MAINTENANCE` (
  `MAINTENANCE_ID` int NOT NULL AUTO_INCREMENT,
  `TASK_TITLE` varchar(50) NOT NULL,
  `VEHICLE_ID` int NOT NULL,
  `SERVICE_DATE` TIMESTAMP DEFAULT NULL,
  `COST` DOUBLE DEFAULT NULL,
  `DESCRIPTION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`MAINTENANCE_ID`),
  KEY `FK_MAINTENANCE_idx` (`VEHICLE_ID`),
  CONSTRAINT `FK_MAINTENANCE` FOREIGN KEY (`VEHICLE_ID`) 
  REFERENCES `MST_VEHICLE` (`VEHICLE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
