CREATE DATABASE  IF NOT EXISTS `BURNING_BROS_SCHEMA`;
USE `BURNING_BROS_SCHEMA`;

--
-- Create table `MST_ROLE`
--

DROP TABLE IF EXISTS `MST_ROLE`;

CREATE TABLE `MST_ROLE` (
  `USER_NAME` varchar(50) NOT NULL,
  `AUTHORITY` varchar(50) NOT NULL,
  UNIQUE KEY `authorities_idx_1` (`USER_NAME`,`AUTHORITY`),
  CONSTRAINT `authorities_ibfk_1` FOREIGN KEY (`USER_NAME`) REFERENCES `MST_USER` (`USER_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `BURNING_BROS_SCHEMA`.`MST_ROLE`
(
`USER_NAME`,
`AUTHORITY`)
VALUES
(
'admin', 
'ROLE_ADMIN');
