CREATE DATABASE  IF NOT EXISTS `BURNING_BROS_SCHEMA`;
USE `BURNING_BROS_SCHEMA`;

--
-- Create table `USERS`
--

DROP TABLE IF EXISTS `MST_USER`;

CREATE TABLE `MST_USER` (
  `USER_ID` int NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(50) NOT NULL,
  `PASSWORD` varchar(68) NOT NULL,
  `ROLES` varchar(50) NOT NULL,
  `ENABLED` boolean DEFAULT true,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

INSERT INTO `BURNING_BROS_SCHEMA`.`MST_USER`
(
`USER_NAME`,
`PASSWORD`,
`ROLES`)
VALUES
(
'admin', 
'{noop}123', 
'ROLE_ADMIN');

INSERT INTO `BURNING_BROS_SCHEMA`.`MST_USER`
(
`USER_NAME`,
`PASSWORD`,
`ROLES`)
VALUES
(
'user1', 
'{noop}123', 
'ROLE_USER');

INSERT INTO `BURNING_BROS_SCHEMA`.`MST_USER`
(
`USER_NAME`,
`PASSWORD`,
`ROLES`)
VALUES
(
'user2', 
'{noop}123', 
'ROLE_USER');
